import type { GalleryItem } from '@/types';

export const galleryItems: GalleryItem[] = [
  {
    id: '1',
    src: '/images/dainty_fineline_flowers.png',
    alt: { ko: '섬세한 꽃 파인라인', en: 'Dainty fine-line flowers' },
    type: 'fine-line',
    dominant: '#FFC3D9',
  },
  {
    id: '2',
    src: '/images/lotus.png',
    alt: { ko: '연꽃 타투', en: 'Lotus tattoo' },
    type: 'fine-line',
    dominant: '#E5E5E5',
  },
  {
    id: '3',
    src: '/images/lotus_2.png',
    alt: { ko: '연꽃 타투 2', en: 'Lotus tattoo 2' },
    type: 'fine-line',
    dominant: '#FFE4E1',
  },
  {
    id: '4',
    src: '/images/dainty_daffodil.png',
    alt: { ko: '섬세한 수선화', en: 'Dainty daffodil' },
    type: 'fine-line',
    dominant: '#FFC3D9',
  },
  {
    id: '5',
    src: '/images/jellyfish_wrist.png',
    alt: { ko: '해파리 손목 타투', en: 'Jellyfish wrist tattoo' },
    type: 'fine-line',
    dominant: '#7DD3FC',
  },
  {
    id: '6',
    src: '/images/rose_chest.png',
    alt: { ko: '장미 가슴 타투', en: 'Rose chest tattoo' },
    type: 'fine-line',
    dominant: '#FFE4E1',
  },
  {
    id: '7',
    src: '/images/rose_sleeve_bw_male.png',
    alt: { ko: '장미 슬리브 흑백', en: 'Rose sleeve black & white' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '8',
    src: '/images/rose_sleeve_bw_male_2.png',
    alt: { ko: '장미 슬리브 흑백 2', en: 'Rose sleeve black & white 2' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '9',
    src: '/images/flaming_heart.png',
    alt: { ko: '불타는 하트', en: 'Flaming heart' },
    type: 'colour',
    dominant: '#FF6B6B',
  },
  {
    id: '10',
    src: '/images/flying_dolphin.png',
    alt: { ko: '날아오르는 돌고래', en: 'Flying dolphin' },
    type: 'colour',
    dominant: '#7DD3FC',
  },
  {
    id: '11',
    src: '/images/snake_lotus_design.png',
    alt: { ko: '뱀과 연꽃 디자인', en: 'Snake & lotus design' },
    type: 'fine-line',
    dominant: '#E5E5E5',
  },
  {
    id: '12',
    src: '/images/kaizen_knee.png',
    alt: { ko: '카이젠 무릎 레터링', en: 'Kaizen knee lettering' },
    type: 'lettering',
    dominant: '#111214',
  },
  {
    id: '13',
    src: '/images/om.png',
    alt: { ko: '옴 심볼', en: 'Om symbol' },
    type: 'lettering',
    dominant: '#111214',
  },
  {
    id: '14',
    src: '/images/skater_boy.png',
    alt: { ko: '스케이터 보이 컬러', en: 'Skater boy color' },
    type: 'colour',
    dominant: '#FFC3D9',
  },
  {
    id: '15',
    src: '/images/skater_boy_bw.png',
    alt: { ko: '스케이터 보이 흑백', en: 'Skater boy black & white' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '16',
    src: '/images/beetle.png',
    alt: { ko: '딱정벌레', en: 'Beetle' },
    type: 'fine-line',
    dominant: '#E5E5E5',
  },
  {
    id: '17',
    src: '/images/beetle_2.png',
    alt: { ko: '딱정벌레 2', en: 'Beetle 2' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '18',
    src: '/images/spider.png',
    alt: { ko: '거미', en: 'Spider' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '19',
    src: '/images/spider_2.png',
    alt: { ko: '거미 2', en: 'Spider 2' },
    type: 'fine-line',
    dominant: '#E5E5E5',
  },
  {
    id: '20',
    src: '/images/little_skull.png',
    alt: { ko: '작은 해골', en: 'Little skull' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '21',
    src: '/images/face_a.png',
    alt: { ko: '얼굴 초상화', en: 'Face portrait' },
    type: 'lettering',
    dominant: '#E5E5E5',
  },
  {
    id: '22',
    src: '/images/lamarcus.png',
    alt: { ko: '라마커스 초상화', en: 'Lamarcus portrait' },
    type: 'fine-line',
    dominant: '#111214',
  },
  {
    id: '23',
    src: '/images/flash.png',
    alt: { ko: '플래시 디자인', en: 'Flash design' },
    type: 'fine-line',
    dominant: '#FFC3D9',
  },
]; 